Proxy all requests - even a repeated one
WireMock-Net/WireMock.Net pull request #1038
Opened 2023-12-11 11:28 UTC by sameena-ops

2023-12-11 11:52 UTC, StefH requested changes

2023-12-11 11:52 UTC, StefH commented on src/WireMock.Net/Owin/WireMockMiddlewareOptions.cs
> +    public bool ProxyAll { get; set; }
add `/// <inheritdoc />`

2023-12-11 11:52 UTC, StefH commented on test/WireMock.Net.Tests/WireMockServer.Proxy.cs
> +        WireMockServerSettings wireMockServerSettings = new WireMockServerSettings
use var

2023-12-11 11:52 UTC, StefH commented on test/WireMock.Net.Tests/WireMockServer.Proxy.cs
> +           WireMockServer server = WireMockServer.Start(wireMockServerSettings);
Do a code-reformat

2023-12-11 12:50 UTC, sameena-ops commented on src/WireMock.Net/Server/WireMockServer.Proxy.cs
> +            proxyRespondProvider.AtPriority(int.MinValue);
pushed the changes

2023-12-11 14:31 UTC, StefH commented on src/WireMock.Net.Abstractions/Admin/Settings/ProxyAndRecordSettingsModel.cs
> +    public bool ProxyAll { get; set; } = false;
This new field should also be parsed like it's done here:
WireMockServerSettingsParser.cs

private static void ParseProxyAndRecordSettings(WireMockServerSettings settings, SimpleSettingsParser parser)

2023-12-11 15:52 UTC, StefH approved these changes

2023-12-11 16:16 UTC, merged

2023-12-12 08:17 UTC, MindaugasLaganeckas commented
Very nice feature! Thank you for working on it! Looking forward to get it released! 😄

2023-12-12 08:31 UTC, StefH commented
It's released.