Implement prefix for saved mapping file
WireMock-Net/WireMock.Net pull request #1040
Opened 2023-12-12 13:12 UTC by MindaugasLaganeckas

2023-12-12 16:13 UTC, StefH requested changes

2023-12-12 16:13 UTC, StefH commented on src/WireMock.Net/Serialization/MappingFileNameSanitizer.cs
> +    private readonly char _replaceChar = '_';
private const char ReplaceChar = '_';

2023-12-12 16:13 UTC, StefH commented on test/WireMock.Net.Tests/Serialization/MappingFileNameSanitizerTests.cs
> +    private readonly string _mappingGuid = "ce216a13-e7d6-42d7-91ac-8ae709e2add1";
both can be const

2023-12-12 16:13 UTC, StefH commented on test/WireMock.Net.Tests/Serialization/MappingFileNameSanitizerTests.cs
> +    private readonly string _mappingTitle =
place this on 1 line

2023-12-13 07:51 UTC, MindaugasLaganeckas commented
Thank you for the feedback! I have addressed all comments and added an extra test for the usecase, that is going to be our primary (somehow missed in the initial implementation).

2023-12-13 10:03 UTC, StefH requested changes

2023-12-13 10:03 UTC, StefH commented on src/WireMock.Net/Serialization/MappingFileNameSanitizer.cs
> +        const string mappingTitlePrefix = "Proxy Mapping for ";
Use the public const value in the ProxyAndRecordSettings class here.

2023-12-13 10:03 UTC, StefH commented on src/WireMock.Net/Settings/ProxyAndRecordSettings.cs
> +    public string PrefixForSavedMappingFile { get; set; } = "Proxy Mapping for ";
Create a public const for this the value in this class.

2023-12-13 10:03 UTC, StefH commented on test/WireMock.Net.Tests/Serialization/MappingFileNameSanitizerTests.cs
> +        var settingsMock = new WireMockServerSettings
officially, this is not mocked, so the name can be `settings`

2023-12-13 10:56 UTC, StefH approved these changes

2023-12-14 07:18 UTC, MindaugasLaganeckas commented
@StefH if it is not too much trouble, may I ask you to release the feature? I would like to start using it as soon as possible  😄

2023-12-14 07:28 UTC, merged

2023-12-14 07:28 UTC, StefH commented
New NuGet will be released today or tomorrow.

2023-12-14 20:23 UTC, StefH commented
NuGet is released

2023-12-15 07:41 UTC, MindaugasLaganeckas commented
I will switch to the latest Wiremock.Net right away for my demo today. Thank you for expediting the release! 🎅

2023-12-15 07:43 UTC, StefH commented
Ah cool. A demo for your company?

2023-12-15 07:44 UTC, MindaugasLaganeckas commented
More like a demo for the team inside the company 😄