Multipart Matcher Fix
WireMock-Net/WireMock.Net pull request #1132
Opened 2024-07-04 19:34 UTC by rmeshksar

Fixes the issue discussed here:
https://github.com/WireMock-Net/WireMock.Net/issues/1119

2024-07-06 18:00 UTC, StefH requested changes

2024-07-06 18:00 UTC, StefH commented on src/WireMock.Net/Matchers/Request/RequestMessageMultiPartMatcher.cs
> +                if ((MatchOperator == MatchOperator.Or && MatchScores.IsPerfect(score))
Can be replaced by?
```
if (MatchOperator is MatchOperator.Or or MatchOperator.And && MatchScores.IsPerfect(score))
```

2024-07-08 16:45 UTC, StefH commented on src/WireMock.Net/Matchers/Request/RequestMessageMultiPartMatcher.cs
> +                if ((MatchOperator == MatchOperator.Or && MatchScores.IsPerfect(score))
@rmeshksar 
Can you take a look at this comment?

2024-07-09 14:09 UTC, rmeshksar commented
@StefH , 
I replied in the conversation for your comment but that message stays in Pending state. 
I repeat it here:


Your suggested if statement and what I did are not the same.
I replicated all possibilities and the two if statement don't match in all cases.

2024-07-09 16:42 UTC, merged