Support RequestBody
WireMock-Net/WireMock.Net pull request #678
Opened 2021-11-05 02:11 UTC by leolplex

Hello @StefH,

I'm trying to add the support to request body, I'm following the same logic used in the response, I'm facing a problem when I try to use `BodyAsJson` in the `RequestModel` 'cause it is not exist, I'm using `Body` but it does not work as I expected, could you have idea why it is happening? 

I appreciate your help.

2021-11-05 11:59 UTC, StefH commented
Can you merge/rebase master into this branch ?

2021-11-08 05:40 UTC, leolplex commented
Hello,

Please skip my first comment I found a solution cast the object with `JsonConvert.SerializeObject` and change the matcher to `JsonMatcher`, please check the last commit.
 Thanks.

2021-11-16 19:39 UTC, StefH commented
@leolplex 
Can you take a look at my comments?

2021-11-16 19:56 UTC, leolplex commented
> @leolplex Can you take a look at my comments?

@StefH
 I am no able to see your comments.

2021-11-16 20:01 UTC, StefH requested changes

2021-11-16 20:09 UTC, leolplex commented
@StefH comments applied!

2021-11-16 20:10 UTC, StefH requested changes

2021-11-16 20:10 UTC, StefH commented on src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs
> +            BodyModel bodyRequestModel = new BodyModel();
`var requestBodyModel = new BodyModel();`

2021-11-16 20:14 UTC, leolplex commented on src/WireMock.Net.OpenApiParser/Mappers/OpenApiPathsMapper.cs
> +            BodyModel bodyRequestModel = new BodyModel();
@StefH Done!

2021-11-16 20:15 UTC, StefH approved these changes

2021-11-16 20:15 UTC, StefH commented
@leolplex 
I'll merge tomorrow and create a new NuGet

2021-11-16 20:16 UTC, leolplex commented
> @leolplex I'll merge tomorrow and create a new NuGet

Thanks a lot @StefH  👍

2021-11-17 07:16 UTC, merged