Added support of custom matchers in static mappings
WireMock-Net/WireMock.Net pull request #713
Opened 2022-01-12 16:34 UTC by levanoz

2022-01-12 17:31 UTC, StefH commented on src/WireMock.Net/Serialization/MatcherMapper.cs
> +                        return _settings.CustomMatcherMapping[matcherName](matcher);
Add `{` and `}`.

2022-01-12 17:32 UTC, StefH commented on src/WireMock.Net/Settings/IWireMockServerSettings.cs
> +        IDictionary<string, Func<MatcherModel, IMatcher>> CustomMatcherMapping { get; set; }
CustomMatcherMappings

2022-01-12 17:32 UTC, StefH commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +                return MatchScores.Mismatch;
Add `{` and `}`.

2022-01-12 18:23 UTC, StefH requested changes
Thank you for this PR.

I think all comments are resolved, but can you double check?

2022-01-12 18:27 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +            //return _pathParams.Values.Select(x => new AnyOf<string, StringPattern>(x)).ToArray();
Yes, I've removed it in latest commit

2022-01-12 18:28 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +                path = path.Substring(0, hashMarkIndex);
I've added them in latest commit

2022-01-12 18:28 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +                path = path.Substring(0, queryParamsIndex);
I've added them in latest commit

2022-01-12 18:28 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +                            return MatchScores.Mismatch;
I've added them in latest commit

2022-01-12 18:28 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +                            return MatchScores.Mismatch;
I've added them in latest commit

2022-01-12 18:28 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +                            return MatchScores.Mismatch;
I've added them in latest commit

2022-01-12 18:29 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/CustomPathParamMatcher.cs
> +                    throw;
I've added them in latest commit

2022-01-12 18:36 UTC, levanoz commented on test/WireMock.Net.Tests/Serialization/MatcherModelMapperTests.cs
> +                var matcherParams = JsonConvert.DeserializeObject<CustomPathParamMatcherModel>((string)model.Pattern);
Added empty line

2022-01-13 16:48 UTC, StefH commented
@levanoz 
Thanks a lot.

Did you test this code change in a real environment?

2022-01-13 17:50 UTC, levanoz commented
> @levanoz Thanks a lot.
> 
> Did you test this code change in a real environment?

@StefH 
My bad, I forgot to run it :( 
I just wrote unit tests for MatcherModelMapper and thought that would be enaugh.
Now I've run it, there was JSON serialization issue, which I've fixed by adding JsonIgnore attribute to CustomMatcherMappings property in settings. Is it okay?
Thanks a lot for reviews.

2022-01-13 18:39 UTC, levanoz commented
> @levanoz I think it's correct for now.
> 
> I was thinking...
> 
> Maybe can you also add a 'real' test like this one:
> 
> https://github.com/WireMock-Net/WireMock.Net/blob/60bdc06d2979a978d2788ef68d300ec22f455960/test/WireMock.Net.Tests/WireMockServerTests.WithBody.cs#L49
> 
> But intead using the wildcardMatcher, use your own test-custom matcher.

@StefH 
I've added two 'real' tests:
https://github.com/WireMock-Net/WireMock.Net/blob/629da5aa2451b837116321a2f286194d25747b74/test/WireMock.Net.Tests/WireMockServerTests.cs#L394
https://github.com/WireMock-Net/WireMock.Net/blob/629da5aa2451b837116321a2f286194d25747b74/test/WireMock.Net.Tests/WireMockServerTests.cs#L442

2022-01-14 11:51 UTC, StefH approved these changes

2022-01-17 13:36 UTC, StefH commented
Later today I'll merge and release a new version.

2022-01-17 13:44 UTC, levanoz commented
@StefH 
Sounds great, thank you!

2022-01-17 15:04 UTC, merged